name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    env:
      NEXT_PUBLIC_BASE_API_URL: https://api.everestdiplomat.org/v1
      NEXT_PUBLIC_IMAGE_API_URL: https://api.everestdiplomat.org

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Set environment variables for build
        run: |
          echo "NEXT_PUBLIC_BASE_API_URL=${NEXT_PUBLIC_BASE_API_URL}" >> .env.production
          echo "NEXT_PUBLIC_IMAGE_API_URL=${NEXT_PUBLIC_IMAGE_API_URL}" >> .env.production

      - name: Build
        run: npm run build

  deploy:
    needs: build
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set environment variables for deployment
        run: |
          echo "NEXT_PUBLIC_BASE_API_URL=${{ secrets.NEXT_PUBLIC_BASE_API_URL }}" >> .env.production
          echo "NEXT_PUBLIC_IMAGE_API_URL=${{ secrets.NEXT_PUBLIC_IMAGE_API_URL }}" >> .env.production

      - name: Deploy to production
        run: |
          pm2 del lyfgram-web:3000 || true
          pm2 start npm --name "lyfgram-web:3000" -- start
